### ISSUE TITLE
How to reobf?

### ISSUE THREAD

**Issue by balaramsudip** [HeartPattern/MC-Remapper#10]
How do you reobf a deobfuscated minecraft jar? the --reobf option gives an error : 

Usage: mcremapperapp [OPTIONS] ARG0 ARG1

Error: Missing argument "ARG1".

**Comment by HeartPattern** [comment]
You must provide input file and mapping file as parameters. Example usage is 
./MC-Remapper input.jar mapping.txt --reobf
However, reobf option currently has no use-case since both forge and bukkit use their own mapping. MC-Remapper is not yet support applying multiple mappings.
