### ISSUE TITLE
Some issue with deobfuscating

### ISSUE THREAD

**Issue by tmvkrpxl0** [HeartPattern/MC-Remapper#11]
I just did test run and i found a problem
when constructor initializes variables, variable names in constructor remains the same
like this

```
  public final float a_changed;

  public constroctor(float ?)
  {
    this.a = ?;
  }
```

**Comment by tmvkrpxl0** [comment]
also, i think it should do something about ? letters
i think ? letters are actually special characters because it was weird characters on the decompiler

**Comment by HeartPattern** [comment]
Is such illegal character used as parameter name in minecraft? I found some variable in localvartable change to snowman unicode, but I didn't found any other special characters.

**Comment by tmvkrpxl0** [comment]
Illegal characters I meant is snowman, sorry about that
My suggestion about the code is, name those arguments as arg1, arg2... And match it by type. And when there's multiple arguments that has same type, match it by order

**Comment by tmvkrpxl0** [comment]
Also there's similar project that's called"Enigma"
https://github.com/FabricMC/Enigma
This might be helpful for you

**Comment by tmvkrpxl0** [comment]
This repository implements feature that i suggested, it automatically renames snowmen to distinguishable arguments name
https://github.com/Jacocococo/MCData

**Comment by HeartPattern** [comment]
For snowman, MC-Remapper already has feature for that. fixlocalvar option change or delete snowman in localvartable.

**Comment by tmvkrpxl0** [comment]
However, i found problem with localvar fixing. 
```
      public final int min;
      public final int max;
  
      public constroctor(int min, int max) {
            this.a = min;
            this.b = max;
      
```
This is constructor of BlockUtil class in 1.16.2. i changed name just in case. there is no variable named a nor b, they should be this.min and this.max. so, how about matching variables by order in cases like this?

**Comment by HeartPattern** [comment]
Perhaps it is a bug in the remapper. I'll analyze that problem.

**Comment by finalchild** [comment]
Did #12 fix the issue?

**Comment by tmvkrpxl0** [comment]
> Did #12 fix the issue?

yes, I didn't test deeply but I tried replacing the deobfuscated jar with the original one, and the game launched successfully

**Comment by HeartPattern** [comment]
Great! I'll close issue. Please reopen issue if some problem related to this issue does not solved.
