### ISSUE TITLE
Change output filename

### ISSUE THREAD

**Issue by Bixilon** [HeartPattern/MC-Remapper#13]
Hi,
thanks for your tool, really a great tool. Helped me a lot.

The name of the output file (`deobfuscated.jar`) is not really good, In some days I won't know which version it is. Also if I deobfuscate multiple versions, I simply don't know what file is from which version.

I suggest to rename the file to the versionname and the ending. For example: `20w46a.jar`

Could you please change it? Thanks

Moritz

**Comment by HeartPattern** [comment]
Since MC-Remapper support not only deobfuscating by passing version number but passing mapping txt file, MC-Remapper cannot know what version it deobfuscate.
Instead, MC-Remapper has --output options that specify output file name. You may use this options.

**Comment by Bixilon** [comment]
Hmm, but then it would make more sense to make `--output` mandatory. And what is if I don't pass files to it (just providing a version)?

**Comment by HeartPattern** [comment]
https://github.com/HeartPattern/MC-Remapper/commit/60d5471207e8969bb1c9577f313979798a5e5d1e
Now, automatically generate from other argument if output argument is absent.
