### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by ConnorHird** [HeartPattern/MC-Remapper#14]
Running the following command gives the following output.
https://pastebin.com/m2uUVBnh
I might be missing something however, I have followed every step, apologies if I have.

**Comment by HeartPattern** [comment]
Can you post mapping.txt you use?

**Comment by ConnorHird** [comment]
> Can you post mapping.txt you use?

https://pastebin.com/cSgFq6tf 
There you go.

**Comment by HeartPattern** [comment]
You should use proguard format mapping file as argument. You can find download link of mapping file from version.json file (File you used), at json path of downloads/client_mapping/url or downloads/server_mappings/url.

You may use either of following link; Link provided in your given file

ClientMapping: https://launcher.mojang.com/v1/objects/ddf517a4f6750f4c15189de4e03246ae1f916cf5/client.txt
ServerMapping: https://launcher.mojang.com/v1/objects/11120c39da4df293c4bd020896391fb9ddd6c2ba/server.txt

**Comment by ConnorHird** [comment]
The program seems to be running fine it's just not deobfuscating the code?
Running >cmd.bat SCP_Lockdown.jar client.txt
Into the console gives the following output.
https://pastebin.com/p8FUZX4E
Re-read the readme like 5 times but still ain't getting nowhere.

**Comment by HeartPattern** [comment]
Can you send me the jar file through heartpattern@heartpattern.io?
