### ISSUE TITLE
Dependency checkout fails due to self signed certificate

### ISSUE THREAD

**Issue by EllaFoxo** [HeartPattern/MC-Remapper#15]
The Nexus repo server at maven.heartpattern.io is currently running a self-signed cert, which is causing the build to fail. Returning to plain old HTTP in the build.gradle solves, this problem temporarily, although SSL would be nice.

**Comment by HeartPattern** [comment]
Now move nexus repo to repo.heartpattern.io with CloudFlare SSL certification. This repo probably solve problem.
