### ISSUE TITLE
--output option has been renamed

### ISSUE THREAD

**Issue by pdinklag** [HeartPattern/MC-Remapper#19]
The `--output` option was renamed to `--output-name` by this commit https://github.com/HeartPattern/MC-Remapper/commit/60d5471207e8969bb1c9577f313979798a5e5d1e. I am not sure whether this is intended, because the examples in the readme still state `--output`. Either the readme or the code should be updated.

**Comment by HeartPattern** [comment]
It was my mistake. Fixed in 61d73514eb55f5842d6b2f40bcfbe3de2193fbbc. Now --ouput and --output-name is both supported.
