### ISSUE TITLE
MC Remapper doesn't remap packaged server jars

### ISSUE THREAD

**Issue by mknjc** [HeartPattern/MC-Remapper#22]
Since 21w39a the server.jar isn't a fat jar anymore and it contains all needed libraries and the server code itself as contained jar files. MC-Remapper only tries to remap the outer jar which only contains the extraction and launch code and not the server code itself.

**Comment by HeartPattern** [comment]
Add support for new structure!
56c88235fa2554989008924e6d763084e3fdb4fc
